service: company-profiler-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2
  profile: eddie-personal
  deploymentMethod: direct
  httpApi:
    cors: true

functions:
  getCompany:
    handler: src/handlers/getCompany.main
    events:
      - httpApi:
          path: /companies/{ticker}
          method: get
  getCompanies:
    handler: src/handlers/getCompanies.main
    events:
      - httpApi:
          path: /companies
          method: get
plugins:
  - serverless-plugin-typescript
  - serverless-offline