service: company-profiler-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2
  profile: eddie-personal
  deploymentMethod: direct

functions:
  getCustomer:
    handler: src/handlers/getCustomer.main
    events:
      - httpApi:
          path: /customers/{id}
          method: get
plugins:
  - serverless-plugin-typescript
  - serverless-offline